# Copyright Contributors to the Open Cluster Management project

changelog:
  exclude:
    labels:
      - ignore-for-release
  categories:
    - title: Breaking Changes 🛠
      labels:
        - breaking-change
    - title: Exciting New Features 🎉
      labels:
        - enhancement
    - title: Bug fixes
      labels:
        - bug
    - title: Other Changes
      labels:
        - "*"
      