# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: {{ .clusterPool.name }}-install-config
  namespace: "{{ .namespace }}"
type: Opaque
data:
  # Base64 encoding of install-config yaml
  install-config.yaml: {{ toYaml .installConfig | b64enc }}