# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: {{ .clusterPool.name }}-pull-secret
  namespace: "{{ .clusterPool.namespace }}"
data:
  .dockerconfigjson: |-
{{ index .pullSecret.data ".dockerconfigjson" | indent 4 }}
type: kubernetes.io/dockerconfigjson