# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
metadata:
  name: {{ .clusterPool.name }}-pull-secret
  namespace: "{{ .namespace }}"
data:
  .dockerconfigjson: {{ .clusterPool.imagePullSecret | b64enc }}
type: kubernetes.io/dockerconfigjson