# Copyright Contributors to the Open Cluster Management project

apiVersion: v1
kind: Secret
type: kubernetes.io/service-account-token
metadata:
  name: "{{ .Name }}"
  namespace: "{{ .Namespace }}"
  annotations:
    kubernetes.io/service-account.name: "{{ .Name }}"