# Copyright Contributors to the Open Cluster Management project


apiVersion: v1
kind: Secret
metadata:
  name: {{ .idp.name }}-secret
  namespace: {{ .authRealm.namespace }}
data:
  bindPassword: {{ .idp.ldap.bindPassword | b64enc }}
type: Opaque
