# Copyright Contributors to the Open Cluster Management project


apiVersion: v1
kind: Secret
metadata:
  name: {{ .authRealm.name }}-client-secret
  namespace: {{ .authRealm.namespace }}
data:
  clientSecret: {{ .idp.github.clientSecret | b64enc }}
type: Opaque
